#################################################################
# +-----------------------------------------------------------+ #
# |                         Weathered                         | #
# |                  Made with <3 by sieadev                  | #
# |             Donate: https://ko-fi.com/sieadev             | #
# |        Source: https://github.com/sieadev/weathered       | #
# +-----------------------------------------------------------+ #
#################################################################

# ---------------------------API Settings---------------------------

# Create an account at openweathermap.org for this
openweatherkey: '**************'

# Syntax 'City,Country'
region: 'Berlin,Germany'

update_interval_seconds: 10

worlds: ['world']

# ------------------------Actionbar Settings------------------------

displayTime: true

displayTemp: true


# ------------------------------Others------------------------------

measurement_system: METRIC