#
#
#

# Weather-Update Timer
update_interval_seconds: 10

# Create an account at openweathermap.org for this
openweatherkey: 'xxx'

# What region's weather would you like to replicate?
# Eg: 'Berlin,Germany', 'London, United Kingdom', 'Paris, France', 'Rome, Italy', 'Madrid, Spain', 'Athens, Greece'
region: 'Berlin,Germany'

# Worlds effected
worlds: ['world']
