#################################################################
# +-----------------------------------------------------------+ #
# |                         Weathered                         | #
# |                  Made with <3 by sieadev                  | #
# |             Donate: https://ko-fi.com/sieadev             | #
# |        Source: https://github.com/sieadev/weathered       | #
# +-----------------------------------------------------------+ #
#################################################################

# ---------------------------API Settings---------------------------

# Create an account at openweathermap.org for this
openweatherkey: '**************'

# Syntax 'City,Country' OR 'City ID' (found by searching for the city on openweathermap.org, it will be at the end of the url)
region: 'Berlin,Germany'
#region: '2950159'

update_interval_seconds: 10

worlds: ['world']

# ------------------------Actionbar Settings------------------------

displayTime: true

displayTemp: true


# ------------------------------Others------------------------------

measurement_system: METRIC